// <auto-generated />
using System;
using DeliciasDaNilda.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DeliciasDaNilda.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DeliciasDaNilda.Domain.Entities.Administrador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("CriadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("NomeCompleto")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasMaxLength(300)
                        .IsUnicode(false)
                        .HasColumnType("varchar(300)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("UX_Administradores_Email");

                    b.ToTable("Administradores", (string)null);
                });

            modelBuilder.Entity("DeliciasDaNilda.Domain.Entities.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CriadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("NomeCompleto")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("WhatsApp")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("WhatsApp")
                        .IsUnique()
                        .HasDatabaseName("UX_Clientes_WhatsApp");

                    b.ToTable("Clientes", (string)null);
                });

            modelBuilder.Entity("DeliciasDaNilda.Domain.Entities.Configuracao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AtualizadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<bool>("WhatsAppBotAtivo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.HasKey("Id");

                    b.ToTable("Configuracoes", (string)null);
                });

            modelBuilder.Entity("DeliciasDaNilda.Domain.Entities.FichaTecnica", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CriadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("SaborId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SaborId")
                        .IsUnique()
                        .HasDatabaseName("UX_FichasTecnicas_SaborId");

                    b.ToTable("FichasTecnicas", (string)null);
                });

            modelBuilder.Entity("DeliciasDaNilda.Domain.Entities.FichaTecnicaItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("FichaTecnicaId")
                        .HasColumnType("int");

                    b.Property<int>("IngredienteId")
                        .HasColumnType("int");

                    b.Property<decimal>("QuantidadePorKg")
                        .HasPrecision(10, 4)
                        .HasColumnType("decimal(10,4)");

                    b.HasKey("Id");

                    b.HasIndex("IngredienteId");

                    b.HasIndex("FichaTecnicaId", "IngredienteId")
                        .IsUnique()
                        .HasDatabaseName("UX_FichaTecnicaItens_Ficha_Ingrediente");

                    b.ToTable("FichaTecnicaItens", (string)null);
                });

            modelBuilder.Entity("DeliciasDaNilda.Domain.Entities.Ingrediente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CriadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<decimal?>("EstoqueMinimoAlerta")
                        .HasPrecision(12, 4)
                        .HasColumnType("decimal(12,4)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<decimal>("SaldoAtual")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(12, 4)
                        .HasColumnType("decimal(12,4)")
                        .HasDefaultValue(0m);

                    b.Property<string>("UnidadeMedida")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique()
                        .HasDatabaseName("UX_Ingredientes_Nome");

                    b.ToTable("Ingredientes", (string)null);
                });

            modelBuilder.Entity("DeliciasDaNilda.Domain.Entities.MovimentoEstoque", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int?>("AdministradorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CriadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("IngredienteId")
                        .HasColumnType("int");

                    b.Property<string>("Motivo")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int?>("PedidoId")
                        .HasColumnType("int");

                    b.Property<decimal>("Quantidade")
                        .HasPrecision(12, 4)
                        .HasColumnType("decimal(12,4)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("AdministradorId");

                    b.HasIndex("PedidoId")
                        .HasDatabaseName("IX_MovimentosEstoque_PedidoId");

                    b.HasIndex("IngredienteId", "CriadoEm")
                        .HasDatabaseName("IX_MovimentosEstoque_IngredienteId_CriadoEm");

                    b.ToTable("MovimentosEstoque", (string)null);
                });

            modelBuilder.Entity("DeliciasDaNilda.Domain.Entities.Pagamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CriadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("FormaPagamento")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("PedidoId")
                        .HasColumnType("int");

                    b.Property<int>("RegistradoPorAdministradorId")
                        .HasColumnType("int");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("Valor")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("PedidoId")
                        .HasDatabaseName("IX_Pagamentos_PedidoId");

                    b.HasIndex("RegistradoPorAdministradorId");

                    b.ToTable("Pagamentos", null, t =>
                        {
                            t.HasCheckConstraint("CK_Pagamentos_Valor_Positivo", "[Valor] > 0");
                        });
                });

            modelBuilder.Entity("DeliciasDaNilda.Domain.Entities.Pedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ConfirmadoEm")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ConfirmadoPorAdministradorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CriadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateOnly>("DataEntrega")
                        .HasColumnType("date");

                    b.Property<TimeOnly?>("HorarioRetirada")
                        .HasColumnType("time");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("Peso")
                        .HasPrecision(6, 3)
                        .HasColumnType("decimal(6,3)");

                    b.Property<decimal>("PrecoPorKgUtilizado")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("SaborId")
                        .HasColumnType("int");

                    b.Property<string>("StatusPagamento")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("SemPagamento");

                    b.Property<string>("StatusPedido")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasDefaultValue("PendenteConfirmacao");

                    b.Property<decimal>("ValorTotal")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId")
                        .HasDatabaseName("IX_Pedidos_ClienteId");

                    b.HasIndex("ConfirmadoPorAdministradorId");

                    b.HasIndex("SaborId");

                    b.HasIndex("DataEntrega", "StatusPedido")
                        .HasDatabaseName("IX_Pedidos_DataEntrega_StatusPedido");

                    b.HasIndex("StatusPedido", "DataEntrega")
                        .HasDatabaseName("IX_Pedidos_StatusPedido_DataEntrega");

                    b.ToTable("Pedidos", null, t =>
                        {
                            t.HasCheckConstraint("CK_Pedidos_Peso_Positivo", "[Peso] > 0");
                        });
                });

            modelBuilder.Entity("DeliciasDaNilda.Domain.Entities.Sabor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CriadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<bool>("Disponivel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<decimal>("PrecoPorKg")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique()
                        .HasDatabaseName("UX_Sabores_Nome");

                    b.ToTable("Sabores", (string)null);
                });

            modelBuilder.Entity("DeliciasDaNilda.Domain.Entities.FichaTecnica", b =>
                {
                    b.HasOne("DeliciasDaNilda.Domain.Entities.Sabor", "Sabor")
                        .WithOne("FichaTecnica")
                        .HasForeignKey("DeliciasDaNilda.Domain.Entities.FichaTecnica", "SaborId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Sabor");
                });

            modelBuilder.Entity("DeliciasDaNilda.Domain.Entities.FichaTecnicaItem", b =>
                {
                    b.HasOne("DeliciasDaNilda.Domain.Entities.FichaTecnica", "FichaTecnica")
                        .WithMany("Itens")
                        .HasForeignKey("FichaTecnicaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DeliciasDaNilda.Domain.Entities.Ingrediente", "Ingrediente")
                        .WithMany("FichaTecnicaItens")
                        .HasForeignKey("IngredienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FichaTecnica");

                    b.Navigation("Ingrediente");
                });

            modelBuilder.Entity("DeliciasDaNilda.Domain.Entities.MovimentoEstoque", b =>
                {
                    b.HasOne("DeliciasDaNilda.Domain.Entities.Administrador", "Administrador")
                        .WithMany("MovimentosEstoque")
                        .HasForeignKey("AdministradorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DeliciasDaNilda.Domain.Entities.Ingrediente", "Ingrediente")
                        .WithMany("MovimentosEstoque")
                        .HasForeignKey("IngredienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DeliciasDaNilda.Domain.Entities.Pedido", "Pedido")
                        .WithMany("MovimentosEstoque")
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Administrador");

                    b.Navigation("Ingrediente");

                    b.Navigation("Pedido");
                });

            modelBuilder.Entity("DeliciasDaNilda.Domain.Entities.Pagamento", b =>
                {
                    b.HasOne("DeliciasDaNilda.Domain.Entities.Pedido", "Pedido")
                        .WithMany("Pagamentos")
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DeliciasDaNilda.Domain.Entities.Administrador", "RegistradoPorAdministrador")
                        .WithMany("PagamentosRegistrados")
                        .HasForeignKey("RegistradoPorAdministradorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Pedido");

                    b.Navigation("RegistradoPorAdministrador");
                });

            modelBuilder.Entity("DeliciasDaNilda.Domain.Entities.Pedido", b =>
                {
                    b.HasOne("DeliciasDaNilda.Domain.Entities.Cliente", "Cliente")
                        .WithMany("Pedidos")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DeliciasDaNilda.Domain.Entities.Administrador", "ConfirmadoPorAdministrador")
                        .WithMany("PedidosConfirmados")
                        .HasForeignKey("ConfirmadoPorAdministradorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DeliciasDaNilda.Domain.Entities.Sabor", "Sabor")
                        .WithMany("Pedidos")
                        .HasForeignKey("SaborId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("ConfirmadoPorAdministrador");

                    b.Navigation("Sabor");
                });

            modelBuilder.Entity("DeliciasDaNilda.Domain.Entities.Administrador", b =>
                {
                    b.Navigation("MovimentosEstoque");

                    b.Navigation("PagamentosRegistrados");

                    b.Navigation("PedidosConfirmados");
                });

            modelBuilder.Entity("DeliciasDaNilda.Domain.Entities.Cliente", b =>
                {
                    b.Navigation("Pedidos");
                });

            modelBuilder.Entity("DeliciasDaNilda.Domain.Entities.FichaTecnica", b =>
                {
                    b.Navigation("Itens");
                });

            modelBuilder.Entity("DeliciasDaNilda.Domain.Entities.Ingrediente", b =>
                {
                    b.Navigation("FichaTecnicaItens");

                    b.Navigation("MovimentosEstoque");
                });

            modelBuilder.Entity("DeliciasDaNilda.Domain.Entities.Pedido", b =>
                {
                    b.Navigation("MovimentosEstoque");

                    b.Navigation("Pagamentos");
                });

            modelBuilder.Entity("DeliciasDaNilda.Domain.Entities.Sabor", b =>
                {
                    b.Navigation("FichaTecnica");

                    b.Navigation("Pedidos");
                });
#pragma warning restore 612, 618
        }
    }
}
